### ISSUE TITLE
docker only links to local images

### ISSUE THREAD

**Issue by ghost** [AsgardEternal/Ubuntu-Ansible-Setup#12]

**Comment by ghost** [comment]
currently we push to the registry in the github actions. the docker compose however uses the local images rather than the registry images.

**Comment by ghost** [comment]
Need way to update the local docker images when we restart/start a service and/or deploy ansible

**Comment by PriceHiller** [comment]
See the [squad server docker compose file](https://github.com/AsgardEternal/Ubuntu-Ansible-Setup/blob/Development/roles/squad-server/templates/docker-compose.yml.j2). It directly references the image in the file along with the registry URL. It will use the latest of whatever tag is in there. Take a look at the server docker entries in the inventory to see the images in use.

This is actively using the registry, since we currently build & push the images on the same system as the registry, using the local is the default because the local _is_ the most up to date image (and it gets added to the registry).

**Comment by ghost** [comment]
if you perform a `docker images` it will list the current images that are in current use/will be used by a docker container. you can also see the build time for them, and currently these are not getting updated unless a manual `docker pull <image>` is performed

**Comment by ghost** [comment]
had to do this for the recent squad update. to get it to work.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16675537/218335028-46e4f118-06d9-4aca-8ca7-96c8d9a4728f.png)
the creation date for the `mee-french-latest` is way behind where it should be. this is normal behavior for docker images it seems as i also had to manually perform a `docker pull` for the mysql image.

**Comment by PriceHiller** [comment]
Ah, I see. This is because we're not issuing a docker compose pull as part of our start up operations. I can fix that this evening. I thought we were doing a pull, apparently not. :/
